### PR TITLE
[refactor][feat]:refactored css and added modal to top

### PR DESCRIPTION
**Pull request by GuptaEesh**
- removed inline styles.
- added modal and it works from everywhere.

### CODE REVIEW

**Review by AnuragSahu11 — APPROVED** [review]
Good use of Css variables, media  queries , Ready to merge

**Review by prachi-sahani — COMMENTED** [review]
The changes look good to merge.
Good that you removed inline styling 😄

**Review by ZuberDunge — APPROVED** [review]
neat and well-structured code, everything looks fine, good to go from my side.

**Comment by GuptaEesh** [comment]
Got 3 reviews merging the branch now.

**Pull request merged**
